### PR TITLE
Fix for LogisticsPipes on Server (See #120)

### PR DESCRIPTION
**Pull request by KorewaLidesu**
Fix crash with server side

EDIT (@darkevilmac) - likely related to #120

### CODE REVIEW

**Comment by darkevilmac** [comment]
What crash is this resolving exactly? Just not sure what's causing this to begin with.

**Comment by KorewaLidesu** [comment]
image

Crash log
[aaaa.txt](https://github.com/TridentMC/ArchitectureCraft/files/10402255/aaaa.txt)

**Comment by darkevilmac** [comment]
Going to pull this in locally and confirm everything compiles and runs as expected.

**Comment by darkevilmac** [comment]
Looks to be working and compiles fine, merging.

**Comment by KorewaLidesu** [comment]
> Looks to be working and compiles fine, merging.

❤️

**Pull request merged**
